#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/ndk

# "booo, bash feature!"
declare -A CMAKE_CONFIGURE_PLATFORM_OPTS WAF_ANDROID_ARCH

CMAKE_CONFIGURE_PLATFORM_OPTS[i386]=-DANDROID_ABI=x86
CMAKE_CONFIGURE_PLATFORM_OPTS[amd64]=-DANDROID_ABI=x86_64
CMAKE_CONFIGURE_PLATFORM_OPTS[arm64]=-DANDROID_ABI=arm64-v8a
CMAKE_CONFIGURE_PLATFORM_OPTS[armv7l]=-DANDROID_ABI=armeabi-v7a

CMAKE_CONFIGURE_OPTS="-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=21 ${CMAKE_CONFIGURE_PLATFORM_OPTS[$GH_CPU_ARCH]}"

WAF_ANDROID_ARCH[i386]=x86
WAF_ANDROID_ARCH[amd64]=x86_64
WAF_ANDROID_ARCH[arm64]=aarch64
WAF_ANDROID_ARCH[armv7l]=armeabi-v7a

WAF_CONFIGURE_OPTS="--android=${WAF_ANDROID_ARCH[$GH_CPU_ARCH]},,21"

USE_CMAKE=1

source scripts/gha/build_common.sh
