name: Build & Deploy HLSDK
on: [push, pull_request]
jobs:
  cleanup:
    runs-on: self-hosted
    steps:
    - name: Cleanup
      run: rm -rf .* || true
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          # GNU/Linux systems
          - os: self-hosted
            targetos: linux
            targetarch: amd64
          - os: self-hosted
            targetos: linux
            targetarch: i386
          - os: self-hosted
            targetos: linux
            targetarch: arm64
          - os: self-hosted
            targetos: linux
            targetarch: armhf

          # Android systems
          - os: self-hosted
            targetos: android
            targetarch: amd64
          - os: self-hosted
            targetos: android
            targetarch: i386
          - os: self-hosted
            targetos: android
            targetarch: arm64
          - os: self-hosted
            targetos: android
            targetarch: armv7l

          # Windows systems
          - os: windows-latest # can be built on GitHub VMs, with relatively latest compiler
            targetos: win32
            targetarch: amd64
          - os: self-hosted # built with older MSVC in Wine to target XP
            targetos: win32
            targetarch: i386


          # macOS systems, built on GitHub macOS VMs
          - os: macos-14 # arm64 as per github documentation
            targetos: apple
            targetarch: arm64
          - os: macos-13 # x86 as per github documentation (will they fix it before they deprecate this version?..)
            targetos: apple
            targetarch: amd64
    env:
      YQ_VERSION: 4.44.6
#      WAFCACHE: ~/wafcache
      WAFCACHE_STATS: 1
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CPU_ARCH: ${{ matrix.targetarch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
#    - name: Cache
#      uses: actions/cache@v4
#      if: ${{ runner.environment == 'github-hosted' }}
#      with:
#        path: ~/wafcache
#        key: ${{ runner.os }}-${{ matrix.targetos }}-${{ matrix.targetarch }}-wafcache
    - name: Install dependencies
      run: bash scripts/gha/${{ runner.environment }}/deps_${{ matrix.targetos }}.sh
    - name: Build HLSDK
      env:
        FWGS_PFX_PASSWORD: ${{ secrets.FWGS_PFX_PASSWORD }}
      run: bash scripts/gha/${{ runner.environment }}/build_${{ matrix.targetos }}.sh
    - name: Upload HLSDK (artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.targetos }}-${{ matrix.targetarch }}
        path: out/*
  release:
    name: "Upload releases"
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Remove old release, fetch artifacts, repackage binaries and upload new release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ github.ref_name == 'master' && 'continuous' || format('continuous-{0}', github.ref_name) }}
      run: |
        gh release delete "$RELEASE_TAG" \
          --yes \
          --cleanup-tag \
          --repo "$GITHUB_REPOSITORY" || true
        sleep 5s
        gh run download "$GITHUB_RUN_ID" \
          --dir out/ \
          --repo "$GITHUB_REPOSITORY"
        pushd out/
        echo "Found artifacts:"
        ls
        for i in $(find -mindepth 1 -maxdepth 1 -type d); do
          mv "$i"/* .
          rm -rf "$i"
        done
        echo "Repackaged artifacts:"
        ls -R
        popd
        sleep 5s
        gh release create "$RELEASE_TAG" out/* \
          --title "HLSDK Mega Continuous ${{ github.ref_name }} Build" \
          --target $GITHUB_SHA \
          --repo "$GITHUB_REPOSITORY" \
          --prerelease
